export const UPDATE_CURRENT_INTERVENTION = 'UPDATE_CURRENT_INTERVENTION';
export const UPDATE_PARTNER_REPORTING_REQUIREMENTS = 'UPDATE_PARTNER_REPORTING_REQUIREMENTS';
export const SHOW_TOAST = 'SHOW_TOAST';
export const CLOSE_TOAST = 'CLOSE_TOAST';
export const INTERVENTION_LOADING = 'INTERVENTION_LOADING';
export const SHOULD_REGET_LIST = 'SHOULD_REGET_LIST';
