import {get as getTranslation} from 'lit-translate/util';
import {GenericObject} from '@unicef-polymer/etools-types';

export const translatesMap: GenericObject = {
  end: 'END_DATE',
  start: 'START_DATE',
  context: 'CONTEXT',
  sections: 'UNICEF_SECTIONS',
  other_info: 'OTHER_INFORMATION',
  result_links: 'RESULTS_STRUCTURE',
  supply_items: 'SUPPLY_CONTRIBUTION',
  equity_rating: 'EQUITY_RATING',
  gender_rating: 'GENDER_RATING',
  flat_locations: 'LOCATIONS',
  planned_budget: 'PLANNED_BUDGET',
  currency: 'DOCUMENT_CURRENCY',
  total_hq_cash_local: 'HQ_CONTRIBUTION',
  hq_support_cost: 'HEADQUARTERS_CONTRIBUTION',
  equity_narrative: 'EQUITY_NARATIVE',
  gender_narrative: 'GENDER_NARATIVE',
  management_budgets: 'EFFECTIVE_EFFICIENT_PROG_MGM',
  applied_indicators: 'PD_INDICATORS',
  activities: 'PD_ACTIVITIES',
  offices: 'UNICEF_OFFICES',
  risks: 'RISKS',
  mitigation_measures: 'PROPOSED_MITIGATION_MEASURES',
  risk_type: 'TYPE',
  cso_cash: 'PARTNER_CASH_BUDGET',
  unicef_cash: 'UNICEF_CASH',
  target: 'TARGET',
  reporting_requirements: 'PARTNER_REPORTING_REQUIREMENTS',
  start_date: 'START_DATE',
  provided_by: 'PROVIDED_BY',
  title: 'GENERAL.TITLE',
  unit_number: 'NUMBER_UNITS',
  other_mentions: 'OTHER_MENTIONS',
  result: 'CP_OUTPUT',
  end_date: 'END_DATE',
  due_date: 'DUE_DATE',
  section: 'SECTION',
  baseline: 'BASELINE',
  locations: 'LOCATIONS',
  is_high_frequency: 'HIGH_FREQ_HUM_IND',
  means_of_verification: 'MEANS_OF_VERIFICATION',
  numerator_label: 'NUMERATOR_LABEL',
  denominator_label: 'DENOMINATOR_LABEL',
  items: 'INPUT_LEVEL_ITEMS',
  name: 'ITEM_DESCRIPTION',
  unit: 'UNIT',
  no_units: 'NUMBER_UNITS',
  act2_partner: () => `${getTranslation('PARTNER_CASH')} for ${getTranslation('TITLE_2')}`,
  act1_partner: () => `${getTranslation('PARTNER_CASH')} for ${getTranslation('TITLE_1')}`,
  act3_partner: () => `${getTranslation('PARTNER_CASH')} for ${getTranslation('TITLE_3')}`,
  act1_unicef: () => `${getTranslation('UNICEF_CASH')} for ${getTranslation('TITLE_1')}`,
  act2_unicef: () => `${getTranslation('UNICEF_CASH')} for ${getTranslation('TITLE_2')}`,
  act3_unicef: () => `${getTranslation('UNICEF_CASH')} for ${getTranslation('TITLE_3')}`,
  technical_guidance: 'TECHNICAL_GUIDANCE',
  capacity_development: 'CAPACITY_DEVELOPMENT',
  sustainability_rating: 'SUSTAINABILITY_RATING',
  implementation_strategy: 'IMPLEMENTATION_STRATEGY_AND_TECHNICAL_GUIDANCE',
  ip_program_contribution: 'OTHER_NON_FINANCIAL_CONTRIBUTION',
  other_partners_involved: 'OTHER_PARTNERS_INVOLVED',
  cash_transfer_modalities: 'CASH_TRANSFER_MOD',
  sustainability_narrative: 'SUSTAINABILITY_NARRATIVE',
  unit_price: 'PRICE_UNIT',
  unicef_product_number: 'UNICEF_PRODUCT_NUMBER',
  ll_results: 'PROGRAM_DOCUMENT_OUTPUT'
};
